from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src     = Glob('*.c')

# Add BLE stack
src     += Glob('ble/*.c')
CPPPATH += [os.path.join(GetCurrentDir(), 'ble')]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
